Devices and external libraries options, make install, Makefile fix
sjperkins/tfopgen pull request #4
Opened 2017-10-09 17:49 UTC by nicolaspi

- New features that allow to generate code according to operator's devices compatibility (cpu and/or gpu), and to specify external libraries to be linked.
- The Makefile has been fixed to work with the latest tensorflow version (tested on the version 1.3 built from source).
- Added 'make install' that copies the built library to the tensorflow's library directory.

2017-10-10 11:16 UTC, nicolaspi commented
Looks like a version issue with tensorflow, the linker does not find  `libtensorflow_framework.so` which was introduced by [this](https://github.com/tensorflow/tensorflow/commit/5c7f9e316d8c7735308a217310350d416d7498cc) commit (19 days ago).

2017-10-13 12:30 UTC, sjperkins commented
Thanks for the PR. It looks like the  new `libtensorflow_framework.so` linking style is going into tensorflow 1.4.0 (see https://github.com/tensorflow/tensorflow/issues/13607 for e.g.). It would probably be best to wait for this release before merging this and releasing a new tfopgen.

2017-10-13 14:35 UTC, sjperkins requested changes

2017-10-13 14:35 UTC, sjperkins commented on tfopgen/create_op.py
> +                         op_type_attrs, op_other_attrs, op_doc, op_libs, op_devices_comps, op_abi):
Move `op_libs, op_devices_comps, op_abi` to a newline.

2017-10-13 14:35 UTC, sjperkins commented on README.rst
I think if we start mixing the Makefile options with the operator options, the yaml will start to be cluttered.

How about a `makefile` section to distinguish it from the rest of the yaml?

```yaml
makefile:
    use_old_abi: yes
    libraries:
       - "m"
```

2017-10-13 14:35 UTC, sjperkins commented on README.rst
> +    devices_compatibilities:
Rename `devices_compatibilities` to `devices`

2017-10-13 14:35 UTC, sjperkins commented on README.rst
> +-  optional external libraries.
`device compatibilities` to `devices`
`optional external libraries` to `makefile` options

2017-10-13 14:35 UTC, sjperkins commented on README.rst
> +Sources codes will be generated according to the specified devices.
`Source code will be generated for the requested devices`

2017-10-13 14:35 UTC, sjperkins commented on README.rst
> +    extra_libraries_deps:
`extra_library_deps` to `libraries`

2017-10-13 14:35 UTC, sjperkins commented on tfopgen/examples/get_slide_patch.yml
> +  - "cpu"
Update with makefile section

2017-10-13 14:35 UTC, sjperkins commented on tfopgen/templates/test_source.j2
> +        {{ perm[0] | replace("'", "") | indent(4, True) }}{{comma(loop.last)}}
What does this do?

2017-10-13 14:35 UTC, sjperkins commented on README.rst
> +
Change to:

```
Note that gcc version 5 and above uses a new C++ ABI.
However, the official tensorflow binary pip packages are built with gcc 4
which uses an older ABI. Set the option `use_old_abi: yes` to make
the library compatible with the older ABI.

2017-10-13 14:35 UTC, sjperkins commented on tfopgen/templates/Makefile.j2
One possible way of handling the the presence or absence of the `-ltensorflow_framework`   library would be to add `tensorflow_version` to the YAML.

2022-10-06 09:23 UTC, closed without merging